### ISSUE TITLE
wc_orders_count Fatal Error

### ISSUE THREAD

**Issue by zwiesman31** [woocommerce/woocommerce-google-analytics-integration#129]
#### What I expected

Updating to version 1.4.5 goes smoothly.

#### What happened instead

When a user updates to 1.4.5, some of them are getting fatal errors like this: 

![http://cld.wthms.co/6Dw10m](http://cld.wthms.co/6Dw10m+)
Image link: http://cld.wthms.co/6Dw10m

Here are cases where this is happening:

* 1515672-zen
* https://wordpress.org/support/topic/fatal-error-on-latest-update-5/
* https://wordpress.org/support/topic/1-4-5-500-error-fatal-error-undefined-function-wc_orders_count/
* https://wordpress.org/support/topic/error-500-after-1-4-5/

#### Steps to reproduce the issue

1. Update to version 1.4.5
2. Doesn't matter if you're on version 3.4.7 or 3.5.0 of WooCommerce, issue remains.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by laurendavissmith** [comment]
Upgrading to critical

**Comment by c-shultz** [comment]
I could not reproduce the error as described. The 1.4.5 release added a call to `wc_orders_count` so the change seems related to the issue that's being described. That being said the `wc_orders_count` function is a WooCommerce resource that should be available as soon as WooCommerce loads. It works totally fine on my end. The only way I found to simulate the issue was to deactivate WooCommerce. 

To help address the fatal error, I added a check in #130 to verify that WooCommerce is activated. This prevents google-analytics from loading if WooCommerce is not available. This is a standard practice that most of our extensions follow.

 @zwiesman31, can you see if the #130 branch resolves the customer issue?

**Comment by c-shultz** [comment]
https://github.com/woocommerce/woocommerce/issues/21676 looks somewhat similar to this issue.

**Comment by c-shultz** [comment]
@superdav42 made an excellent observation that this could be occurring if an upgrade resulted in WooCommerce being deactivated. Since google-analytics 1.4.5 will cause a fatal failure without WooCommerce, a workaround for this situation would be to:

1. Temporarily rename the `woocommerce-google-analytics` plugin folder to restore site.
2. Reactivate WooCommerce
3. Restore the folder name to `woocommerce-google-analytics`

**Comment by laurendavissmith** [comment]
@zwiesman31 can you see if this may be the issue

**Comment by zwiesman31** [comment]
@laurendavissmith I asked on the ticket and two .org posts but haven't gotten a reply yet.

Just asked for updates.
