### ISSUE TITLE
Standard tracking still on WC pages even if disabled

### ISSUE THREAD

**Issue by jessepearson** [woocommerce/woocommerce-google-analytics-integration#137]
If **Enable Standard Tracking** is unchecked, the standard tracking code is still displayed on WooCommerce pages. This appears to happen here:
https://github.com/woocommerce/woocommerce-google-analytics-integration/blob/1.4.7/includes/class-wc-google-analytics.php#L297-L300

I would have expected the setting to be pulled and the standard tracking code to *not* be displayed if the box was not checked. Is the standard tracking code needed to be able to track the eCommerce events from WC pages with products? Since this has been like this for 5+ years, I believe it's working as it should, would just like clarification. 

#### Steps to reproduce the issue

1. Install and set up as shown in the below screenshots
1. Visit a product page in a private browsing window
1. Check the source, the code is displayed

![](http://cld.wthms.co/FgDpDm+)
Image Link: http://cld.wthms.co/FgDpDm

![](http://cld.wthms.co/RnK5Gx+)
Image Link: http://cld.wthms.co/RnK5Gx

Forum thread reference:
https://wordpress.org/support/topic/same-web-property-id-is-tracked-twice-3/

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by dchenk** [comment]
@jessepearson thanks for addressing this issue. I think you're moving this in the right direction. But I believe that leaving "Standard Tracking" unchecked should make it so that the standard Analytics tracking code doesn't show up on any pages, so I don't understand why the code should still be inserted on the Order Received page. I'm sure I'm missing something. Could you please clarify?

One thing I should note is that any e-commerce events emitted should be emitted relatively late in the page loading process so that the Google Analytics code has already been loaded in (especially if it's being inserted by Google Tag Manager).

**Comment by xnosek00** [comment]
Hi, I have the same problem. I'm using google tag manager which is insertig google analytics code. So I unchecked: "Enable standard tracking" in your plugin.

Main page is OK (https://janekdo.cz), but when I enter this page (https://janekdo.cz/workshopy/) with products, google tag assistant says: Same web property ID is tracked twice. 

![image](https://user-images.githubusercontent.com/1574100/53303488-0ea71d80-386b-11e9-9577-8b410aef0802.png)

**Comment by alexanderkladov** [comment]
Hey everyone,

@johndcoy (who is this plugin's support team member), created an official bug report on GitHub (#143 ) for this, after I reported the same problem [on their WordPress.org support forum](https://wordpress.org/support/topic/compatibility-issues-with-gadwp-2/).

So we'll hopefully see a bug fix released for this soon.

Regards,
Alex

**Comment by budzanowski** [comment]
Closing in favor of #143.
