### ISSUE TITLE
Standard Tracking disabled still tracks data

### ISSUE THREAD

**Issue by johndcoy-zz** [woocommerce/woocommerce-google-analytics-integration#143]
#### What I expected

Unchecking the **Standard Tracking** feature under _WooCommerce > Settings > Integration_ should stop tracking data after disabled.

#### What happened instead

Unchecking the **Standard Tracking** feature under _WooCommerce > Settings > Integration_ continues tracking data after once enabled, then disabled.

![Screenshot](https://cld.wthms.co/OpTyTV+)
Screenshot link: https://cld.wthms.co/OpTyTV

![Screenshot](https://cld.wthms.co/j24c9Z+)
Screenshot link: https://cld.wthms.co/j24c9Z

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by om4james** [comment]
Hi @johndcoy, i have submitted a possible fix for this in PR #144, would it be possible to have it reviewed?

This bug is pretty bad for anyone using another analytics plugin plus this plugin for eCommerce tracking, as it results in duplicate page views across all the WooCommerce parts of the site. 

Thanks!

**Comment by om4james** [comment]
Hi WooCommerce,

This is a pretty major bug that is likely affecting *many* WooCommerce stores.

Could you please review PR #144, where I have proposed a solution to the issue? It's disappointing that the proposed fix hasn't been reviewed or acknowledged in the 2 months since it was submitted.

Thank you for your time.

James

**Comment by AashikP** [comment]
Updating priority to `Critical` as this breaks the core functionality of the extension itself.

**Comment by roykho** [comment]
Reopening this as we will be reverting this PR here https://github.com/woocommerce/woocommerce-google-analytics-integration/pull/144 which caused another critical here https://github.com/woocommerce/woocommerce-google-analytics-integration/issues/145

**Comment by alexanderkladov** [comment]
@roykho I strongly disagree with this decision. That's not a critical error. That's a settings miss-configuration on the user's side. If they haven't enabled standard tracking via this plugin & also haven't added standard tracking code via any other means, then how on earth are they expecting any tracking to work? That's their mistake and they need to fix their settings. Maybe send them a warning via admin email or smth. But choosing to re-introduce a serious bug instead is a bad decision.

That should not have been reverted IMHO.

**Comment by roykho** [comment]
@alexanderkladov - You can use this filter `wc_goole_analytics_send_pageview` if you want to disable standard `send pageview`.

**Comment by alexanderkladov** [comment]
> @alexanderkladov - You can use this filter `wc_goole_analytics_send_pageview` if you want to disable standard `send pageview`.

@roykho Yeah, that's a good trick for developers, but that doesn't fix the fact that a very important core setting of this plugin is broken to a general user. Which, in my opinion, is a critical issue that should have been resolved months ago, when it was reported (and a PR solution submitted).

Everyone, who got no reports in their Google Analytics after the 1.4.10 update, have configured THEIR plugin settings incorrectly and they need to fix them sooner or later. Or are we intending to keep this bug in circulation forever?

I think, it's safe to assume, that in the next update we can just set "Enable Standard Tracking" by default for everyone, who still has this plugin currently activated on their site, since before 1.4.10 (and now after the roll-back in 1.4.11), the "Enable Standard Tracking" is ignored anyway and is always added to all pages, regardless of the settings. That means that overriding this setting to "Enabled" for everyone on <=1.4.11, wouldn't make any difference to their site. Then, at the same time, we can re-introduce the proposed v1.4.10 fix and those, who will untick that setting from v1.4.12 onwards, will finally get the pesky "Standard Tracking" scripts to disappear, without having to resort to using unnecessary hooks & filters.

**Comment by budzanowski** [comment]
After 1.4.20 release we need to update the documentation with filter info.

**Comment by budzanowski** [comment]
Closing. The filter should be used. New typo-less name is available:
`wc_google_analytics_send_pageview`
