### ISSUE TITLE
Sales are not recorded in Google Analytics

### ISSUE THREAD

**Issue by grigorijurasov** [woocommerce/woocommerce-google-analytics-integration#164]
#### What I expected

For sales to be recorded

#### What happened instead

Sales are not recorded.

#### Steps to reproduce the issue

1. Set up Google Analytics.
2. Make sure enhanced e-commerce is enabled on Woo and Google Analytics sides.
3. Place an order in incognito browser window.
4. The visit is recorded but the sale is not.

More reports here:

https://wordpress.org/support/topic/ecommerce-tracking-stopped/#post-12738755

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by bor0** [comment]
This is weird, 3 reports within a week but the last release was a month ago. I will check it.

**Comment by ahmadssb** [comment]
I don't it has anything to do with your plugin woocommerce-google-analytics-integration
Nor using Google site kit plugin
Nor using integration code tracking manually .

in fact I was disabling your plugin I just activated to check if it'll work. but unfortunatly nothing appears

just to explain the issue 

in my website the issue appears on 25 March 2020 there is no tracking 

![image](https://user-images.githubusercontent.com/4236683/80767206-0eca3980-8b50-11ea-973e-12af59c733b9.png)

but when you compare it with facebook pixel data you can see that there were events on the website

![image](https://user-images.githubusercontent.com/4236683/80767134-e3dfe580-8b4f-11ea-9a44-e4f58f18e887.png)


in fact I have another website in wordpress but doesn't use woocommerce and using code tracking manually.  it is working fine

![image](https://user-images.githubusercontent.com/4236683/80768434-12ab8b00-8b53-11ea-92e8-540e544c7b31.png)


additionally these errors appears on console (not sure if there is anything related to the issue)

![image](https://user-images.githubusercontent.com/4236683/80768586-79c93f80-8b53-11ea-8d07-c1f9f4e8ea12.png)

**Comment by bor0** [comment]
I am unable to reproduce this. I tried purchasing several products on different versions, they all work for me.

<img width="1445" alt="Screen Shot 2020-05-01 at 13 19 40" src="https://user-images.githubusercontent.com/1620929/80802062-7ca54e00-8bae-11ea-8d59-0a5ceae3b57e.png">

These are my settings:

<img width="1658" alt="Screen Shot 2020-05-01 at 13 14 02" src="https://user-images.githubusercontent.com/1620929/80801762-a742d700-8bad-11ea-9017-fdb38673302b.png">

The only reason I can think of this not tracking data is if the `Enable Universal Analytics` is unchecked? If that really is the case, we can improve the UI to not allow checking `Enable enhanced eCommerce` unless `Enable Universal Analytics` is also checked.

@grigorijurasov could you please provide additional info?

**Comment by moo2web** [comment]
Hi, I'm the one the 'more reports' refers to.
Just adding more info that might be helpful. Let me know if I can provide anything else.

I've checked my settings:
`Enable Universal Analytics` is ticked. 
All settings boxes were ticked except `Anonymize IP addresses`
I've just ticked that also to see if that makes any difference.

No transactions in GA showing since 28April (which shows only 1 of the 6 transactions for that day)

![image](https://user-images.githubusercontent.com/38910437/80927225-77374600-8df0-11ea-94ca-ef09abd25ebf.png)

**Comment by bor0** [comment]
@moo2web could you please check if there's a network request to Google for the particular product once you reach the order completed page?

**Comment by moo2web** [comment]
@bor0 sorry I'm not sure how to do that.

However, I may have resolved my instance of the problem:
I used the Softaculous staging to create a copy of the site at dev.belowthekowhai.nz for update testing. 
The dev site had copied the WooCommerce Google Analytics Integration plugin, including the tracking number in the settings.

I created a new GA property for the dev site, and used that new tracking code in the plugin settings for the dev site.

I've since seen 2 of 2 transactions successfully showing in GA for the original property/tracking code!

**Comment by bor0** [comment]
This is great news, thank you for your detailed explanation @moo2web!

When you say "created a new GA property", does that mean a new GA tracking code or something else?

**Comment by moo2web** [comment]
@bor0 yes that's correct. A new Property in Google Analytics, which has it's own Tracking ID. (its actually the same base number, with a different suffix)

Going forward I'll need to ensure whenever I create a staging copy of the site, I must remember to change the staging site's tracking code in the plugin settings, to avoid this conflict again.

Unless there is a way this could be coded in the plugin to prevent this scenario?

**Comment by bor0** [comment]
I just want to confirm, the issue occurred for you because you had 2 different sites using the same GA code?

**Comment by moo2web** [comment]
@bor0 at this stage, I believe so. I'm waiting for more sales to be created so I can be sure it is fully working again since removing the tracking code from the dev site.

I'm wary that the 2 sales so far could be anomalies as even when both sites had the same tracking code, occasional transactions would still make it through somehow (but not all).

If it helps, I can post back in here after a day or two to report how many sales have been made, and how many have successfully shown in GA.

**Comment by bor0** [comment]
@moo2web please, that would definitely help, and thank you! This looks like a configuration issue after all so it would be best for us to figure out when it is happening.

**Comment by moo2web** [comment]
Hi, I'm back to confirm I've seen 12 sales since and all have shown in GA! 

Warning to others, ensure you don't have two sites with same tracking code in the plugin settings.
Does this mean anyone could accidentally cripple someone elses stats by using their tracking code also?

**Comment by hctrbz** [comment]
I am experiencing the same issue.

I was not getting any tracking at all with the plugin including any e-commerce tracking.

After trying multiple things I removed my domain from the Set Domain Name field in the plugin settings.

Then I started to see Real Time traffic but still no e-commerce tracking.

I tried this on my existing GA property and a new property for the same website. It doesn't seem to register any e-commerce activity in GA.

**Comment by grigorijurasov** [comment]
@bor0 sorry for the delay. I can confirm that the "enable universal analytics" checkbox was ticked, I did not have two sites with the same tracking code connected to one account.

Since reporting this, I've seen at least one site functioning correctly and I do see a purchase in Google Analytics from the end of April right now so I suppose there was a delay or misconfiguration of some sort but eventually it worked.
