### ISSUE TITLE
Missing filter for gtag snippet in case of purchase event

### ISSUE THREAD

**Issue by jesus225** [woocommerce/woocommerce-google-analytics-integration#189]
#### What I expected

For the plugin to allow filtering snippet output on purchase events.

#### What happened instead

Available filters are not covering purchase events.

#### Steps to reproduce the issue

Hello!

I am currently using the filter "woocommerce_gtag_snippet" to modify main snippet output to remove text/javascript and change it for text/plain. This is to make it compatible with GDPR plugins which will only change it back to text/javascript and therefore actually execute the code after the user has consent.

I am using native woocomerce filter to do the same with the JQuery you inline in product pages.

This works well for most of the events except for purchase which is actually the most important. There is no filter in your code to modify the output so it always has the <script type='text/javascript'> and it causes purchase event to execute before main snippet is even loaded, missing the purchase event.

Could you please consider adding an additional filter for this purpose in your code (function get_ecommerce_tracking_code( $order_id ))?

Thank you in advance.
Regards.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by edirpedro** [comment]
This plugin has similar problems like in "Facebook for Woocommerce" when validating cookies law. I'd like to attach here the discussion from that other plugin because the same feature could be added in both plugins to enable developers to build a custom check on the client side instead of the server side that is not trustworthy when you are caching your website.

https://github.com/woocommerce/facebook-for-woocommerce/issues/301#issuecomment-1095252894

**Comment by martynmjones** [comment]
As part of the upcoming version `2.0.0` release, we have implemented [Consent mode](https://github.com/woocommerce/woocommerce-google-analytics-integration/pull/361) which addresses the GDPR requirements mentioned so I'm closing this issue.
