### ISSUE TITLE
Use product_id instead of sku

### ISSUE THREAD

**Issue by saghelani** [woocommerce/woocommerce-google-analytics-integration#295]
Is it possible to have a flag so that `get_product_identifier` returns `$product->get_id()` instead of `$product->get_sku()`?

The google merchant centre product feed is setup such that the merchant centre item_id is the woocommerce product id instead of the sku. 

This causes misalignment in google analytics.

Also why is the product id prepended by a hash? Does this get parsed in google analytics and linked to the google merchant centre item correctly?

**Comment by ianlin** [comment]
Thanks for reporting this @saghelani.

> Is it possible to have a flag so that get_product_identifier returns $product->get_id() instead of $product->get_sku()?

We will discuss it as it also needs to consider backward compatibility, will get back to you once we have a conclusion.

> why is the product id prepended by a hash? Does this get parsed in google analytics and linked to the google merchant centre item correctly?

The reason the product ID was prepended by a `#` came from this PR #89 which solved #78 where it originally came from [the issue here](https://wordpress.org/support/topic/this-is-why-it-doesnt-work/?replies=1#post-). In short, if it’s prepended by a hash, it’s an ID, otherwise a SKU. As far as I understand it would make it consistent across all tracking events but I don't think it would be parsed and linked to the item in Google Merchant Center.

**Comment by jorgemd24** [comment]
Closing this issue as it was resolved by https://github.com/woocommerce/woocommerce-google-analytics-integration/pull/309
