### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'map')     at actions.js

### ISSUE THREAD

**Issue by opr** [woocommerce/woocommerce-google-analytics-integration#341]
### Describe the bug:

When running this plugin and using the WooCommerce Cart and Checkout blocks, I see this error in my console.

```
TypeError: Cannot read properties of undefined (reading 'map')
    at actions.js?ver=2e50f7862892acedba0f:1:740
```

I believe the related file and line is https://github.com/woocommerce/woocommerce-google-analytics-integration/blob/trunk/assets/js/src/tracking.js#L108

### Steps to reproduce:

1. Set up Google Analytics
2. Use the Cart/Checkout Blocks
3. Add items to your cart and go to the Checkout page.
4. See the error in JS console.

### Expected behavior:

No errors.

### Actual behavior:

Error mentioned above.

**Comment by eason9487** [comment]
In backtracking on this issue, found that this also includes another issue, which is that there is the `experimental__woocommerce_blocks-checkout-render-checkout-form` event tracking has been lost for over two years. (Ref: https://github.com/woocommerce/woocommerce-blocks/pull/4745)

Since WooCommerce Blocks 10.8.0, which was bundled into Woo 8.1.0, the data structure was changed by https://github.com/woocommerce/woocommerce-blocks/pull/10254. Therefore, this issue also happens on [the other four tracking](https://github.com/woocommerce/woocommerce-google-analytics-integration/blob/1.8.11/assets/js/src/actions.js#L35-L56) when calling the `trackCheckoutStep` function.

Since WooCommerce Blocks 11.5.0, which was bundled into Woo 8.4.0, the missing event was added back by https://github.com/woocommerce/woocommerce-blocks/pull/11554, resulting in this issue occurring when entering the checkout page.
