### ISSUE TITLE
Bounce Rate Changes When Plugin Is Activated

### ISSUE THREAD

**Issue by dcoleonline** [woocommerce/woocommerce-google-analytics-integration#76]
A user is seeing distinct changes in bounce rate when the plugin is active vs inactive. They've reported the following after having it disabled for two weeks, and enabled for another two weeks:

**First Two Weeks (Plugin NOT Activated)**
- 46.4% on home page
- 47.24% on shop page
- between 45-75% for the product pages

**Last Two Weeks (Plugin Activated)**
- 19.89% on the homepage
- 19.61% on the shop page 
- between 17-18 % on each of the product pages

**Additional Details About Static Pages**
- 50% About TréLuxe' page (over 2 months - plugin disabled)
- 0% About TréLuxe' page (over 2 weeks - plugin active)
- 16.67% About Products page (over 2 months - plugin disabled)
- 14.29% About Products page (over 2 weeks - plugin active)

**Site:** http://discovertreluxe.com
(from ticket ID 381043)

**Comment by matt-h** [comment]
The plugin is not currently active on the site so I can't say for sure, but usually bounce rate issues are due to duplicate GA code on the site. Especially with the About page at 0% this would be my first guess.

Either the current code wasn't removed to be replaced by the plugin or the plugin wasn't configured properly to go along with it.

It also could have been events firing on page load as that counts the page as not bouncing.

**Comment by chrisblakley** [comment]
I've noticed that the plugin adds a `ga( 'send', 'pageview' );` to the bottom of the page. If you are sending a pageview outside of the plugin then you may be sending two pageviews to Google Analytics.

**Comment by laurendavissmith** [comment]
It could also be the order in which the GA code is loaded in the activated vs/ not-activated examples. There are too many variables at play here to fix anything within the extension itself.

Closing for now but we can reopen if this becomes larger issue
