### ISSUE TITLE
Fatal Error when using Enhanced eCommerce Product Detail Views and WooCommerce [product] shortcodes

### ISSUE THREAD

**Issue by om4james** [woocommerce/woocommerce-google-analytics-integration#81]
If you have the "Product Detail Views" "Enhanced eCommerce" setting enabled, and you use a `[product id="x"]` shortcode on a WordPress page, a fatal error occurs:

`Call to a member function get_sku() on a non-object in wp-content/plugins/woocommerce-google-analytics-integration/includes/class-wc-google-analytics-js.php on line 445`

Also reported here: https://wordpress.org/support/topic/bug-conflict?replies=1

**Comment by mikkamp** [comment]
I've done some additional testing regarding this situation.
The product_detail section is only triggered on the following hook: woocommerce_after_single_product

So with a default install of WooCommerce this would only occur when using the shortcode `[product_page id="x"]`

Another prerequisite to trigger this bug is to have either related products or upsell products to show up.

When the product_page shortcode is used it creates a custom WP_Query loop and then uses the single-product template. At the end of the template of content-single-product the upsell_display and related_product sections are displayed.

Each of these two creates another WP_Query loop and then calls `wp_reset_postdata()`. This causes the loop to be reset to the main loop which in this case is the main page and not the product being displayed in the shortcode.

So when the hook woocommerce_after_single_product is called at the end of the template content-single-product the query has been reset so any calls to get the product id will return the ID of the main page.

**Comment by johnson5487** [comment]
Any sort of ETA on when this will be fixed?

**Comment by hamzahali** [comment]
still getting
Fatal error: Call to undefined function monsterinsights_get_ua_to_output() in /home/mpristine/public_html/wp-content/plugins/woocommerce-google-analytics-proy/includes/class-wc-google-analytics-pro-integration.php on line 818

**Comment by mikkamp** [comment]
@hamzahali That error looks like it's from the WooCommerce Google Analytics Pro plugin. That's a different plugin. For help with the WooCommerce Google Analytics Pro plugin I would suggest to contact WooCommerce Support at: https://woocommerce.com/contact-us/
