### ISSUE TITLE
Missing Google Analytics ID

### ISSUE THREAD

**Issue by Babelfisch** [woocommerce/woocommerce-google-analytics-integration#93]
After your last update, the plugin does't work, because there is a bug in `class-wc-google-analytics-js.php` line 234:

```php
$ga_snippet_create = self::tracker_var() . "( 'create', '" . esc_js( $ga_id ) . "', '" . $set_domain_name . "' );";
```

Variable `$ga_id` is nowhere defined and the ID is empty in the analytics code:

```javascript
ga( 'create', '', 'my.shop.url' );
```

My workaround is this line before the upper line:

```php
$ga_id = self::get( 'ga_id' );
```

**Comment by Babelfisch** [comment]
The bug is already reported ten months ago #84 with a PR but no one cares? 😠

**Comment by petergullberg** [comment]
Thanks, it stopped working after this last update, and this fixed it...

**Comment by shawaj** [comment]
Same problem here! How was this mission critical plugins not tested?

Comical and embarrassing for WooCommerce / WordPress

**Comment by hertzdog** [comment]
Hi, same problem here. Thank you for your solution! 

I think the file you are referring to is:

class-wc-google-analytics-js.php

(note the final js)

**Comment by Babelfisch** [comment]
Oh, my mistake. `class-wc-google-analytics-js.php` is right and I changed it.

**Comment by mitch827** [comment]
unbelievable bug that got pushed live. Thanks for the fix.

**Comment by braders** [comment]
This bug is also blocking me making a decision on whether on not to use this plugin for a site I am working on, so it would be great to have an indication of when this might be fixed. 

It's unclear if any maintainers at WooCommerce/ Automattic have been notified of this issue, so I am just going to CC' in the most frequent recent contributors of this Repo, to see if we can move things forward: @bor0 @justinshreve (Apologies, if this is just noise, but a quick comment with an estimated fix date would be appreciated so we know that their is progress.)

**Comment by bor0** [comment]
cc @mattyza for prioritization
